//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megazinde.Models.DB.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberlerTeknolojis
    {
        public int h_teknoloji_id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public string icerik1 { get; set; }
        public string icerik2 { get; set; }
        public string resim { get; set; }
        public string video { get; set; }
        public string tarih { get; set; }
        public int tiklanma { get; set; }
    }
}
