//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megazinde.Models.DB.DbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMegazindeEntities : DbContext
    {
        public DbMegazindeEntities()
            : base("name=DbMegazindeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Duyurulars> Duyurulars { get; set; }
        public virtual DbSet<HaberlerDogas> HaberlerDogas { get; set; }
        public virtual DbSet<HaberlerFilms> HaberlerFilms { get; set; }
        public virtual DbSet<HaberlerIndexes> HaberlerIndexes { get; set; }
        public virtual DbSet<HaberlerModas> HaberlerModas { get; set; }
        public virtual DbSet<Haberlers> Haberlers { get; set; }
        public virtual DbSet<HaberlerSeyahats> HaberlerSeyahats { get; set; }
        public virtual DbSet<HaberlerSpors> HaberlerSpors { get; set; }
        public virtual DbSet<HaberlerTeknolojis> HaberlerTeknolojis { get; set; }
        public virtual DbSet<Heads> Heads { get; set; }
        public virtual DbSet<Kategorilers> Kategorilers { get; set; }
        public virtual DbSet<Kullanicilars> Kullanicilars { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yorumlars> Yorumlars { get; set; }
    }
}
