//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megazinde.Models.DB.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlars
    {
        public int yorum_id { get; set; }
        public string yorum { get; set; }
        public string tarih { get; set; }
        public Nullable<int> Haberler_h_id { get; set; }
        public Nullable<int> Kategoriler_kategori_id { get; set; }
        public string Kullanicilar_kullaniciadi { get; set; }
    
        public virtual Haberlers Haberlers { get; set; }
        public virtual Kategorilers Kategorilers { get; set; }
        public virtual Kullanicilars Kullanicilars { get; set; }
    }
}
